[package]
name = "suisec_dojo"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.42.2", override = true }

[addresses]
suisec_dojo = "0x0"
